version: '3.8'

services:
  db:
    image: postgres:15
    container_name: service_catalog_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_catalog
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "service_catalog"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@db:5432/service_catalog?sslmode=disable",
      "up"
    ]

  seed:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://user:password@db:5432/service_catalog?sslmode=disable
    command: ["./seed"]


  app:
    build: .
    depends_on:
      seed:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/service_catalog?sslmode=disable
      JWT_SECRET: my-secret
    command: ["./main"]


volumes:
  pgdata:
